// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdftBEMMXABPzQHasXJFJ9JCuepCuQtDc',
    appId: '1:612799014923:web:52f51198f133da0d7cff0e',
    messagingSenderId: '612799014923',
    projectId: 'community-97298',
    authDomain: 'community-97298.firebaseapp.com',
    storageBucket: 'community-97298.firebasestorage.app',
    measurementId: 'G-YZCVD7MDJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNrcYQ8AO59VdOZFDdJ0IyKGJ7Z2QnFAI',
    appId: '1:612799014923:android:7ce30a82c68616c37cff0e',
    messagingSenderId: '612799014923',
    projectId: 'community-97298',
    storageBucket: 'community-97298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_LzQRSfweMZBsfW5aDCWBWhbiz1SchNA',
    appId: '1:612799014923:ios:e89aada1048a24c77cff0e',
    messagingSenderId: '612799014923',
    projectId: 'community-97298',
    storageBucket: 'community-97298.firebasestorage.app',
    iosBundleId: 'com.example.free',
  );
}
